StacksAndQueues/SPOJ-ProblemJNext-Editorial-PD.md, StacksAndQueues/SPOJ-ProblemJNext-PD.java
Some optimisation method for editorial of the problem
=> Add minor update to editorial

StacksAndQueues/SPOJ-ProblemSTPAR-Editorial-PD.md
New additions to the directory Stacks And Queues
=> Add new Stacks And Queues Problem Solution and Editorial

README.md, StacksAndQueues/SPOJ-ProblemMMASS-Editorial-PD.md, StacksAndQueues/SPOJ-ProblemMMASS-PD.java
Added solution and editorial to Problem MMASS from SPOJ
=> Create Solution and Editorial to Problem MMASS

StacksAndQueues/SPOJ-ProblemHISTOGRA-Editorial-PD.md, StacksAndQueues/SPOJ-ProblemHISTOGRA-PD.java
Added solution and editorial to problem HISTOGRA from SPOJ
=> Create SPOJ Problem HISTOGRA Solution and Editorial

StacksAndQueues/CodeForces-Problem281D-Editorial-PD.md, StacksAndQueues/CodeForces-Problem281D-PD.java
Added solution and editorial to CodeChef problem maximum XOR
=> Create CodeChef problem max XOR solution and editorial

Euclid-s GCD and HCF Algorithm/BasicEuclideanAlgorithm-PD.cpp, Euclid-s GCD and HCF Algorithm/ExtendedEuclideanAlgorithm-PD.java, Euclid-s GCD and HCF Algorithm/Readme.md
Added new directory for Euclidean algorithm.
=> Add Eculid's HCF Algorithm

Primes/TopCoder-ProblemPrimePoly-Editorial-PD.md, Primes/TopCoder-ProblemPrimePoly-PD.java
Added solution and editorial to problem PrimePoly
=> Create PrimePoly solution and Editorial

Arrays/CodeChef-ProblemLeCandy-Editorial-PD.md, Arrays/CodeChef-ProblemLeCandy-PD.java, Arrays/ReadMe.md, Primes/ReadMe.md, Primes/TopCoder-ProblemPrimeAna-Editorial-PD.md, Primes/TopCoder-ProblemPrimeAna-PD.java, README.md
Added multiples files and updated many ReadMe.mdS
=> Add multiple solutions, editorial and updates to ReadMe

Arrays/CodeChef-ProblemCNote-Editorial-PD.md, Arrays/CodeChef-ProblemCNote-PD.java, Arrays/ReadMe.md, README.md
added problem solutions and editorials and updates readme
=> Create problem solution and editorial and update ReadMe

Arrays/CodeChef-ProblemSalary-Editorial-PD.md, Arrays/CodeChef-ProblemSalary-PD.java, Arrays/ReadMe.md
Added Salary problem solution and editorial
=> Create Salary problem solution and editorial

Arrays/CodeChef-ProblemRainbowA-Editorial-PD.md, Arrays/CodeChef-ProblemRainbowA-PD.java, Arrays/ReadMe.md
Added solution and editorial to problem Rainbow Array and updated readme.md
=> Create RainbowA solution and editorial

Arrays/CodeChef-ProblemCops-Editorial-PD.md, Arrays/CodeChef-ProblemCops-PD.java, Arrays/ReadMe.md
Added new solution and editorial and edited readme
=> Create solution and editorial to problem Cops and update readme

Primes/ReadMe.md, README.md, Strings/CodeChef-ProblemCSUB-Editorial-PD.md, Strings/CodeChef-ProblemCSUB-PD.java, Strings/ReadMe.md
Added new solutions and updated multiple readme.md
=> Create solution and editorial to problems and update multiple readme

Basic Recursion/ReadMe.md, Greedy Algorithms/CodeChef-ProblemCHEFST-PD.java, Greedy Algorithms/ReadMe.md
Added new files and updated old ones
=> Create new solution and update readMe

Greedy Algorithms/CodeChef-ProblemCAKEDOOM-PD.java, Greedy Algorithms/CodeChef-ProblemTADELIV-PD.java, Greedy Algorithms/ReadMe.md, README.md
Added new solutions and updates to repo
=> Create multiple problem solutions and updates

Greedy Algorithms/CodeChef-ProblemMMPROD-PD.java, Greedy Algorithms/ReadMe.md, README.md
Added new solutions to the problems and updated readme
=> Create new solutions and updates to readme

Greedy Algorithms/CodeChef-ProblemCHEFTMA-PD.java, Greedy Algorithms/CodeChef-ProblemSTICKS-PD.java, Greedy Algorithms/ReadMe.md
Add new solutions and updates to readme
=> Create new solution to problems and update readme

Greedy Algorithms/ReadMe.md, Greedy Algorithms/SPOJ-ProblemBAISED-PD.java, Greedy Algorithms/SPOJ-ProblemBALIFE-PD.java, Sorting Algorithms/ReadMe.md
Add new problem solutions and updates to readme
=> Create new solutions and update readme

Greedy Algorithms/ReadMe.md, Greedy Algorithms/SPOJ-ProblemGCJ101BB-PD.java
Add SPOJ problem solution and update in readme
=> Create SPOJ problem solution 

Dynamic Programming/ReadMe.md, Greedy Algorithms/CodeChef-ProblemMAXDIFF-PD.java
=> Update MAXDIFF correct solution

Greedy Algorithms/CodeChef-ProblemLEMUSIC-Editorial-PD.md, Greedy Algorithms/CodeChef-ProblemLEMUSIC-PD.java, Greedy Algorithms/ReadMe.md
Add new solutions to problem and update readme
=> Create new problem solutions and update readme

Dynamic Programming/HackerRank, Dynamic Programming/HackerRank/CoinChange.java, Dynamic Programming/HackerRank/ReadMe.md
=> Add CoinChange code

Dynamic Programming/HackerRank/ReadMe.md, Dynamic Programming/HackerRank/SherlockAndCost.java, README.md
=> Add Sherlock and Cost solution
